
---

- name: "Playbook to test NAPALM-Ansible"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Retrieve device facts via NAPALM"
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"    # To run playbook, change to: ansible_host 
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result }}"
