---

- name: "Loop test"
  hosts: all
  gather_facts: true
  connection: network_cli

  tasks:
    - name: "Loop through IP info"
      debug:
        msg: "{{ ansible_facts }}"
      #  msg: "{{ ansible_facts['net_hostname'] }} has an IP address of : {{ item }} configured"
      #loop: "{{ ansible_facts['net_all_ipv4_address'] }}"